likipe_blog:
    resource: "@LikipeBlogBundle/Resources/config/routing.yml"
    prefix:   /backend

Likipe_DataAPI:
    resource: "@LikipeDataAPIBundle/Resources/config/routing.yml"
    prefix:   /api
    
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"