LikipeBlogBundle_Post_add:
    pattern:  /add
    defaults: { _controller: "LikipeBlogBundle:Post:add" }

LikipeBlogBundle_Post_index:
    pattern:  /{iPage}
    defaults: { _controller: "LikipeBlogBundle:Post:index", iPage: 1 }
    
LikipeBlogBundle_Post_edit:
    pattern:  /edit/{iPostId}
    defaults: { _controller: "LikipeBlogBundle:Post:edit" }
    
LikipeBlogBundle_Post_delete:
    pattern:  /delete/{iPostId}
    defaults: { _controller: "LikipeBlogBundle:Post:delete" }