parameters:
#    likipe_data_api.example.class: Likipe\DataAPIBundle\Example

services:
#    likipe_data_api.example:
#        class: %likipe_data_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
