LikipeBlogBundle_index:
    pattern:  /
    defaults: { _controller: LikipeBlogBundle:Default:index }
    
LikipeBlogBundle_Post:
    resource:   "@LikipeBlogBundle/Resources/config/routes/post.yml"
    prefix:   /post
