LikipeBlogBundle_index:
    pattern:  /dashboard
    defaults: { _controller: LikipeBlogBundle:Default:index }
    
LikipeBlogBundle_Post:
    resource:   "@LikipeBlogBundle/Resources/config/routes/post.yml"
    prefix:   /post
    
LikipeBlogBundle_Blog:
    resource:   "@LikipeBlogBundle/Resources/config/routes/blog.yml"
    prefix:   /blog
    
LikipeBlogBundle_User:
    resource:   "@LikipeBlogBundle/Resources/config/routes/user.yml"
    prefix:   /user
 
LikipeBlogBundle_Security_login:
    pattern:  /login
    defaults: { _controller: "LikipeBlogBundle:Security:login" }

LikipeBlogBundle_Security_login_check:
    pattern:  /login_check

LikipeBlogBundle_Security_logout:
    pattern:  /logout
    defaults: { _controller: "LikipeBlogBundle:Security:logout" }

LikipeBlogBundle_ckeditor_browser_url:
    pattern:  /ckeditor-browser
    defaults: { _controller: "LikipeBlogBundle:Default:configCKeditor" }
