LikipeBlogBundle_index:
    pattern:  /
    defaults: { _controller: LikipeBlogBundle:Default:index }
    
LikipeBlogBundle_Post:
    resource:   "@LikipeBlogBundle/Resources/config/routes/post.yml"
    prefix:   /post
    
LikipeBlogBundle_Blog:
    resource:   "@LikipeBlogBundle/Resources/config/routes/blog.yml"
    prefix:   /blog
    
LikipeBlogBundle_User:
    resource:   "@LikipeBlogBundle/Resources/config/routes/user.yml"
    prefix:   /user
