parameters:
    likipe_blogbundle_services_log.class:      Likipe\BlogBundle\Services\LogService

services:
    likipe.blog.log:
        class: %likipe_blogbundle_services_log.class%
        arguments: ["@service_container"]
