parameters:
#    likipe_blog.example.class: Likipe\BlogBundle\Example

services:
#    likipe_blog.example:
#        class: %likipe_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
